# 4.1 numpy ndarray:多维数组对象

In [1]:
import numpy as np

data = np.random.randn(2,3)
data

array([[ 0.82207005,  0.97783946, -1.32904761],
       [-0.65043021,  0.78438995, -1.44196734]])

In [2]:
data * 10

array([[  8.2207005 ,   9.77839456, -13.29047609],
       [ -6.50430211,   7.84389947, -14.41967338]])

每一个数组都有一个shape属性，用来表征数组每一维度的数量；每一个数组都有一个dtype属性，用来描述数组的数据类型；

In [3]:
data.shape

(2, 3)

In [4]:
data.dtype

dtype('float64')

## 4.1.1 生成ndarray

In [5]:
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [6]:
data2 = [[1,2,4,3],[3,2,1,1]]
arr2 = np.array(data2)
arr2

array([[1, 2, 4, 3],
       [3, 2, 1, 1]])

In [7]:
arr2.ndim

2

In [8]:
arr2.shape

(2, 4)

In [9]:
arr1.dtype

dtype('float64')

In [10]:
arr2.dtype

dtype('int32')

给定长度及形状后，np.zeros()可以创建全0数组；np.ones()可以创建全1数组；np.empty()创建没有初始化数值得数组。

In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [13]:
np.empty((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

## 4.1.2 ndarray的数据类型

数据类型，即dtype

In [14]:
arr1 = np.array([1,2,3],dtype=np.float64)
arr1.dtype

dtype('float64')

In [15]:
arr2 = np.array([1,2,3],dtype=np.int32)
arr2.dtype

dtype('int32')

可以使用astype方式转换数据的类型。

In [16]:
arr = np.array([1,2,3,4])
arr.dtype

dtype('int32')

In [17]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

也可以用一个数组的dtype属性来表示另一个数组的属性。

In [19]:
int_array = np.arange(10)
calibers = np.array([.22,.270,.93,.44,.42], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [21]:
empty_uint32 = np.empty(8,dtype='u4')
empty_uint32

array([       1,        1,        0,  6029370,      136,        0,
       16777984,    32767], dtype=uint32)

## 4.1.3 Numpy数组算术

数组之所以重要是因为它允许你进行批量操作而无须任何for循环。Numpy用户称这种特性为**向量化**

In [22]:
arr = np.array([[1., 2., 3.],[4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [23]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [24]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

会把计算参数传递给每一个元素。

In [25]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [26]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

同尺寸数组间比较，会产生一个布尔值数组。

In [28]:
arr2 = np. array([[2,5,3],[1,0,4]])
arr2 > arr

array([[ True,  True, False],
       [False, False, False]])

## 4.1.4 基础索引与切片

如果传入一个数值给数组的切片，数值被传递给整个切片。

In [29]:
arr = np.arange(10)
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

区别于python的内建列表，数组的切片是原数组的仕途。这意味着数据不是被复制，任何对于视图的修改都会反映到原数组上。

In [30]:
arr_slice = arr[5:8]
arr_slice[1] = 12344
arr

array([    0,     1,     2,     3,     4,    12, 12344,    12,     8,
           9])

因为Numpy处理大数据，所以如果复制太多会引起内存占用过大，所以估计后续对于切片的操作会比较常见。如果想要对切片进行拷贝，需要显式的拷贝，例如：
arr[5:8].copy

在一个二维数组中，每个索引值对应的元素不再是一个值，而是一个一维数组。

In [31]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
arr2d[1]

array([4, 5, 6])

In [33]:
arr2d[1][2]

6

In [34]:
arr2d[1,2]

6

多维数组中，省略后续索引值，返回的对象将是降低一个维度的数组。**（这个要关注，不是很直观的理解）**

In [35]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [36]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
arr3d[1,1]

array([10, 11, 12])

In [38]:
arr3d[1,1,2]

12

### 4.1.4.1 数组的切片索引

与Python类似，数组可以通过类似语法进行切片。

In [40]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
arr2d[1:,:2]

array([[4, 5],
       [7, 8]])

In [43]:
arr2d[1:,:2] = 0
arr2d

array([[1, 2, 3],
       [0, 0, 6],
       [0, 0, 9]])

## 4.1.5 布尔索引